language: python
python:
  - "2.7"
  - "3.3"
env:
  - LXML_VERSION=2.3
  - LXML_VERSION=3.2.3
install:
  - pip install -q grako --use-mirrors
  - pip install -q lxml==$LXML_VERSION --use-mirrors
  - pip install -q uTidylib --use-mirrorss
cript: make -C tests
